name: CI workflow
# Events
on: 
  push:
    branches: ["main"] 
  pull_request:
    branches: ["main"]

#Build on the previous actions

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
